### ISSUE TITLE
Hook: Tracy

### ISSUE THREAD

**Issue by solcik** [contributte/monolog#11] opened 2019-05-29 15:10 UTC
Related: #4, #6 

Only one from/to needs to be enabled and the other disabled.
If both are enabled (current default settings), then you get into recursion.

<img width="829" alt="Screenshot 2019-05-29 17 09 12" src="https://user-images.githubusercontent.com/1543737/58568469-9fa7df00-8234-11e9-9c17-c5ba6036b058.png">

**Comment by mabar** [comment] 2019-05-29 15:12
Recursion is caused by statically created original logger, dependencies itself are not cyclical. We are already working on workaround.

**Comment by mabar** [comment] 2019-05-30 08:55
Here is the root of all issues, causing our lazy adapter cyclically depending on itself. Fixed by https://github.com/contributte/monolog/commit/b2461ced0dff5f43245678cd690d279426b35d25.

```
public function createServiceTracy__logger(): Tracy\ILogger
{
	$service = Tracy\Debugger::getLogger();
	return $service;
}
```

**Closed as completed** 2019-05-30 09:02 UTC
